//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokatun.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pokatun.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ChooseRoleText {
            get {
                return ResourceManager.GetString("ChooseRoleText", resourceCulture);
            }
        }
        
        public static string TouristRoleDescriptionText {
            get {
                return ResourceManager.GetString("TouristRoleDescriptionText", resourceCulture);
            }
        }
        
        public static string HotelRoleDescriptionText {
            get {
                return ResourceManager.GetString("HotelRoleDescriptionText", resourceCulture);
            }
        }
        
        public static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        public static string HelloCaps {
            get {
                return ResourceManager.GetString("HelloCaps", resourceCulture);
            }
        }
        
        public static string PreEntranceDescriptionText {
            get {
                return ResourceManager.GetString("PreEntranceDescriptionText", resourceCulture);
            }
        }
        
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        public static string IStillDoesntHaveAccText {
            get {
                return ResourceManager.GetString("IStillDoesntHaveAccText", resourceCulture);
            }
        }
        
        public static string IHaveAccText {
            get {
                return ResourceManager.GetString("IHaveAccText", resourceCulture);
            }
        }
    }
}
