//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokatun.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pokatun.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        public static string ChooseRoleText {
            get {
                return ResourceManager.GetString("ChooseRoleText", resourceCulture);
            }
        }
        
        public static string TouristRoleDescriptionText {
            get {
                return ResourceManager.GetString("TouristRoleDescriptionText", resourceCulture);
            }
        }
        
        public static string HotelRoleDescriptionText {
            get {
                return ResourceManager.GetString("HotelRoleDescriptionText", resourceCulture);
            }
        }
        
        public static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        public static string HelloCaps {
            get {
                return ResourceManager.GetString("HelloCaps", resourceCulture);
            }
        }
        
        public static string PreEntranceTouristDescriptionText {
            get {
                return ResourceManager.GetString("PreEntranceTouristDescriptionText", resourceCulture);
            }
        }
        
        public static string PreEntranceHotelDescriptionText {
            get {
                return ResourceManager.GetString("PreEntranceHotelDescriptionText", resourceCulture);
            }
        }
        
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        public static string EntranceToAccount {
            get {
                return ResourceManager.GetString("EntranceToAccount", resourceCulture);
            }
        }
        
        public static string ToComeIn {
            get {
                return ResourceManager.GetString("ToComeIn", resourceCulture);
            }
        }
        
        public static string IStillDoesntHaveAccText {
            get {
                return ResourceManager.GetString("IStillDoesntHaveAccText", resourceCulture);
            }
        }
        
        public static string IHaveAccText {
            get {
                return ResourceManager.GetString("IHaveAccText", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string Further {
            get {
                return ResourceManager.GetString("Further", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string USREOU {
            get {
                return ResourceManager.GetString("USREOU", resourceCulture);
            }
        }
        
        public static string InvalidUSREOU {
            get {
                return ResourceManager.GetString("InvalidUSREOU", resourceCulture);
            }
        }
        
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        public static string CardNumberOrIBAN {
            get {
                return ResourceManager.GetString("CardNumberOrIBAN", resourceCulture);
            }
        }
        
        public static string FullCompanyName {
            get {
                return ResourceManager.GetString("FullCompanyName", resourceCulture);
            }
        }
        
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        public static string GetCode {
            get {
                return ResourceManager.GetString("GetCode", resourceCulture);
            }
        }
        
        public static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        public static string FullnameRequiredMessage {
            get {
                return ResourceManager.GetString("FullnameRequiredMessage", resourceCulture);
            }
        }
        
        public static string HotelNameRequiredMessage {
            get {
                return ResourceManager.GetString("HotelNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string CompanyNameRequiredMessage {
            get {
                return ResourceManager.GetString("CompanyNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string BankNameRequiredMessage {
            get {
                return ResourceManager.GetString("BankNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string InvalidPhoneNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberMessage", resourceCulture);
            }
        }
        
        public static string ValidBankCardOrIbanNotDefined {
            get {
                return ResourceManager.GetString("ValidBankCardOrIbanNotDefined", resourceCulture);
            }
        }
        
        public static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        public static string PasswordMismatchMessage {
            get {
                return ResourceManager.GetString("PasswordMismatchMessage", resourceCulture);
            }
        }
        
        public static string IncorrectPasswordError {
            get {
                return ResourceManager.GetString("IncorrectPasswordError", resourceCulture);
            }
        }
        
        public static string HotelNumberAllreadyExistsError {
            get {
                return ResourceManager.GetString("HotelNumberAllreadyExistsError", resourceCulture);
            }
        }
        
        public static string HotelNumberDoesntExistError {
            get {
                return ResourceManager.GetString("HotelNumberDoesntExistError", resourceCulture);
            }
        }
        
        public static string AccountAllreadyExistsError {
            get {
                return ResourceManager.GetString("AccountAllreadyExistsError", resourceCulture);
            }
        }
        
        public static string AccountDoesNotExistError {
            get {
                return ResourceManager.GetString("AccountDoesNotExistError", resourceCulture);
            }
        }
        
        public static string IbanAllreadyRegisteredError {
            get {
                return ResourceManager.GetString("IbanAllreadyRegisteredError", resourceCulture);
            }
        }
        
        public static string UsreouAllreadyRegisteredError {
            get {
                return ResourceManager.GetString("UsreouAllreadyRegisteredError", resourceCulture);
            }
        }
        
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        public static string InvalidTokenError {
            get {
                return ResourceManager.GetString("InvalidTokenError", resourceCulture);
            }
        }
        
        public static string ExpiredTokenError {
            get {
                return ResourceManager.GetString("ExpiredTokenError", resourceCulture);
            }
        }
        
        public static string ProcessingRequest {
            get {
                return ResourceManager.GetString("ProcessingRequest", resourceCulture);
            }
        }
        
        public static string SavePassword {
            get {
                return ResourceManager.GetString("SavePassword", resourceCulture);
            }
        }
        
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        public static string WriteRegistrationEmailMessage {
            get {
                return ResourceManager.GetString("WriteRegistrationEmailMessage", resourceCulture);
            }
        }
        
        public static string WriteVerificationCodeMessage {
            get {
                return ResourceManager.GetString("WriteVerificationCodeMessage", resourceCulture);
            }
        }
        
        public static string ActiveBid {
            get {
                return ResourceManager.GetString("ActiveBid", resourceCulture);
            }
        }
        
        public static string BidsArchive {
            get {
                return ResourceManager.GetString("BidsArchive", resourceCulture);
            }
        }
        
        public static string MyBids {
            get {
                return ResourceManager.GetString("MyBids", resourceCulture);
            }
        }
        
        public static string MyRates {
            get {
                return ResourceManager.GetString("MyRates", resourceCulture);
            }
        }
        
        public static string MyHotelNumbers {
            get {
                return ResourceManager.GetString("MyHotelNumbers", resourceCulture);
            }
        }
        
        public static string HotelRating {
            get {
                return ResourceManager.GetString("HotelRating", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string ConditionsAndLoyaltyProgram {
            get {
                return ResourceManager.GetString("ConditionsAndLoyaltyProgram", resourceCulture);
            }
        }
        
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        public static string HotelInfo {
            get {
                return ResourceManager.GetString("HotelInfo", resourceCulture);
            }
        }
        
        public static string AddPhone {
            get {
                return ResourceManager.GetString("AddPhone", resourceCulture);
            }
        }
        
        public static string AddLink {
            get {
                return ResourceManager.GetString("AddLink", resourceCulture);
            }
        }
        
        public static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        public static string HotelLocationAddress {
            get {
                return ResourceManager.GetString("HotelLocationAddress", resourceCulture);
            }
        }
        
        public static string HotelLocationAddressDidntSetted {
            get {
                return ResourceManager.GetString("HotelLocationAddressDidntSetted", resourceCulture);
            }
        }
        
        public static string CheckInTime {
            get {
                return ResourceManager.GetString("CheckInTime", resourceCulture);
            }
        }
        
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        public static string CheckInTimeDidntSetted {
            get {
                return ResourceManager.GetString("CheckInTimeDidntSetted", resourceCulture);
            }
        }
        
        public static string CheckOutTime {
            get {
                return ResourceManager.GetString("CheckOutTime", resourceCulture);
            }
        }
        
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        public static string CheckOutTimeDidntSetted {
            get {
                return ResourceManager.GetString("CheckOutTimeDidntSetted", resourceCulture);
            }
        }
        
        public static string SiteOrSocialNetworkLink {
            get {
                return ResourceManager.GetString("SiteOrSocialNetworkLink", resourceCulture);
            }
        }
        
        public static string SymbolsLeftFormat {
            get {
                return ResourceManager.GetString("SymbolsLeftFormat", resourceCulture);
            }
        }
        
        public static string WithinTerritory {
            get {
                return ResourceManager.GetString("WithinTerritory", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string WithinTerritoryFillingInstruction {
            get {
                return ResourceManager.GetString("WithinTerritoryFillingInstruction", resourceCulture);
            }
        }
        
        public static string DescriptionFillingInstruction {
            get {
                return ResourceManager.GetString("DescriptionFillingInstruction", resourceCulture);
            }
        }
        
        public static string HotelPhotoDidntChoosen {
            get {
                return ResourceManager.GetString("HotelPhotoDidntChoosen", resourceCulture);
            }
        }
        
        public static string WithinTerritoryDescriptionDidntAdded {
            get {
                return ResourceManager.GetString("WithinTerritoryDescriptionDidntAdded", resourceCulture);
            }
        }
        
        public static string HotelDescriptionDidntAdded {
            get {
                return ResourceManager.GetString("HotelDescriptionDidntAdded", resourceCulture);
            }
        }
        
        public static string PhoneNumbersArentSetted {
            get {
                return ResourceManager.GetString("PhoneNumbersArentSetted", resourceCulture);
            }
        }
        
        public static string LinksArentSetted {
            get {
                return ResourceManager.GetString("LinksArentSetted", resourceCulture);
            }
        }
        
        public static string InvalidPhones {
            get {
                return ResourceManager.GetString("InvalidPhones", resourceCulture);
            }
        }
        
        public static string PhonesDuplication {
            get {
                return ResourceManager.GetString("PhonesDuplication", resourceCulture);
            }
        }
        
        public static string LinksDuplication {
            get {
                return ResourceManager.GetString("LinksDuplication", resourceCulture);
            }
        }
        
        public static string CompleteYourProfile {
            get {
                return ResourceManager.GetString("CompleteYourProfile", resourceCulture);
            }
        }
        
        public static string Infrastructure {
            get {
                return ResourceManager.GetString("Infrastructure", resourceCulture);
            }
        }
        
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        public static string ProfileChanging {
            get {
                return ResourceManager.GetString("ProfileChanging", resourceCulture);
            }
        }
        
        public static string NewHotelNumber {
            get {
                return ResourceManager.GetString("NewHotelNumber", resourceCulture);
            }
        }
        
        public static string HotelNumberEditing {
            get {
                return ResourceManager.GetString("HotelNumberEditing", resourceCulture);
            }
        }
        
        public static string RoomNumber {
            get {
                return ResourceManager.GetString("RoomNumber", resourceCulture);
            }
        }
        
        public static string Econom {
            get {
                return ResourceManager.GetString("Econom", resourceCulture);
            }
        }
        
        public static string Standart {
            get {
                return ResourceManager.GetString("Standart", resourceCulture);
            }
        }
        
        public static string Lux {
            get {
                return ResourceManager.GetString("Lux", resourceCulture);
            }
        }
        
        public static string SelectRoomCategory {
            get {
                return ResourceManager.GetString("SelectRoomCategory", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string RoomsNumFormat {
            get {
                return ResourceManager.GetString("RoomsNumFormat", resourceCulture);
            }
        }
        
        public static string PeopleNumFormat {
            get {
                return ResourceManager.GetString("PeopleNumFormat", resourceCulture);
            }
        }
        
        public static string PromptAmoutOfRoms {
            get {
                return ResourceManager.GetString("PromptAmoutOfRoms", resourceCulture);
            }
        }
        
        public static string PromptAmoutOfVisitors {
            get {
                return ResourceManager.GetString("PromptAmoutOfVisitors", resourceCulture);
            }
        }
        
        public static string IncorrectInput {
            get {
                return ResourceManager.GetString("IncorrectInput", resourceCulture);
            }
        }
        
        public static string HotelNumberDescription {
            get {
                return ResourceManager.GetString("HotelNumberDescription", resourceCulture);
            }
        }
        
        public static string NumbersCleaning {
            get {
                return ResourceManager.GetString("NumbersCleaning", resourceCulture);
            }
        }
        
        public static string Nutrition {
            get {
                return ResourceManager.GetString("Nutrition", resourceCulture);
            }
        }
        
        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        public static string Supper {
            get {
                return ResourceManager.GetString("Supper", resourceCulture);
            }
        }
        
        public static string HotelNumberPriceHint {
            get {
                return ResourceManager.GetString("HotelNumberPriceHint", resourceCulture);
            }
        }
        
        public static string DiscountHint {
            get {
                return ResourceManager.GetString("DiscountHint", resourceCulture);
            }
        }
        
        public static string PriceHint {
            get {
                return ResourceManager.GetString("PriceHint", resourceCulture);
            }
        }
        
        public static string RoomNumberDidntSetted {
            get {
                return ResourceManager.GetString("RoomNumberDidntSetted", resourceCulture);
            }
        }
        
        public static string PriceDidntSetted {
            get {
                return ResourceManager.GetString("PriceDidntSetted", resourceCulture);
            }
        }
        
        public static string DiscountDidntSetted {
            get {
                return ResourceManager.GetString("DiscountDidntSetted", resourceCulture);
            }
        }
        
        public static string NeedSetupNumberDescription {
            get {
                return ResourceManager.GetString("NeedSetupNumberDescription", resourceCulture);
            }
        }
        
        public static string HotelNumber {
            get {
                return ResourceManager.GetString("HotelNumber", resourceCulture);
            }
        }
        
        public static string RoomsCounter {
            get {
                return ResourceManager.GetString("RoomsCounter", resourceCulture);
            }
        }
        
        public static string VisitorsCounter {
            get {
                return ResourceManager.GetString("VisitorsCounter", resourceCulture);
            }
        }
        
        public static string AddedHotelNumbersCounter {
            get {
                return ResourceManager.GetString("AddedHotelNumbersCounter", resourceCulture);
            }
        }
        
        public static string InHotelNumber {
            get {
                return ResourceManager.GetString("InHotelNumber", resourceCulture);
            }
        }
        
        public static string NotIncluded {
            get {
                return ResourceManager.GetString("NotIncluded", resourceCulture);
            }
        }
        
        public static string SubmitBid {
            get {
                return ResourceManager.GetString("SubmitBid", resourceCulture);
            }
        }
        
        public static string BidSubmittionInfo {
            get {
                return ResourceManager.GetString("BidSubmittionInfo", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
    }
}
