//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokatun.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pokatun.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ChooseRoleText {
            get {
                return ResourceManager.GetString("ChooseRoleText", resourceCulture);
            }
        }
        
        public static string TouristRoleDescriptionText {
            get {
                return ResourceManager.GetString("TouristRoleDescriptionText", resourceCulture);
            }
        }
        
        public static string HotelRoleDescriptionText {
            get {
                return ResourceManager.GetString("HotelRoleDescriptionText", resourceCulture);
            }
        }
        
        public static string Tourist {
            get {
                return ResourceManager.GetString("Tourist", resourceCulture);
            }
        }
        
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        public static string HelloCaps {
            get {
                return ResourceManager.GetString("HelloCaps", resourceCulture);
            }
        }
        
        public static string PreEntranceTouristDescriptionText {
            get {
                return ResourceManager.GetString("PreEntranceTouristDescriptionText", resourceCulture);
            }
        }
        
        public static string PreEntranceHotelDescriptionText {
            get {
                return ResourceManager.GetString("PreEntranceHotelDescriptionText", resourceCulture);
            }
        }
        
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        public static string EntranceToAccount {
            get {
                return ResourceManager.GetString("EntranceToAccount", resourceCulture);
            }
        }
        
        public static string ToComeIn {
            get {
                return ResourceManager.GetString("ToComeIn", resourceCulture);
            }
        }
        
        public static string IStillDoesntHaveAccText {
            get {
                return ResourceManager.GetString("IStillDoesntHaveAccText", resourceCulture);
            }
        }
        
        public static string IHaveAccText {
            get {
                return ResourceManager.GetString("IHaveAccText", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string Further {
            get {
                return ResourceManager.GetString("Further", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string USREOU {
            get {
                return ResourceManager.GetString("USREOU", resourceCulture);
            }
        }
        
        public static string InvalidUSREOU {
            get {
                return ResourceManager.GetString("InvalidUSREOU", resourceCulture);
            }
        }
        
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        public static string CardNumberOrIBAN {
            get {
                return ResourceManager.GetString("CardNumberOrIBAN", resourceCulture);
            }
        }
        
        public static string FullCompanyName {
            get {
                return ResourceManager.GetString("FullCompanyName", resourceCulture);
            }
        }
        
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        public static string HotelNameRequiredMessage {
            get {
                return ResourceManager.GetString("HotelNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string CompanyNameRequiredMessage {
            get {
                return ResourceManager.GetString("CompanyNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string BankNameRequiredMessage {
            get {
                return ResourceManager.GetString("BankNameRequiredMessage", resourceCulture);
            }
        }
        
        public static string InvalidPhoneNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPhoneNumberMessage", resourceCulture);
            }
        }
        
        public static string ValidBankCardOrIbanNotDefined {
            get {
                return ResourceManager.GetString("ValidBankCardOrIbanNotDefined", resourceCulture);
            }
        }
        
        public static string InvalidEmailMessage {
            get {
                return ResourceManager.GetString("InvalidEmailMessage", resourceCulture);
            }
        }
        
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        public static string PasswordMismatchMessage {
            get {
                return ResourceManager.GetString("PasswordMismatchMessage", resourceCulture);
            }
        }
        
        public static string AccountAllreadyExistsError {
            get {
                return ResourceManager.GetString("AccountAllreadyExistsError", resourceCulture);
            }
        }
        
        public static string IbanAllreadyRegisteredError {
            get {
                return ResourceManager.GetString("IbanAllreadyRegisteredError", resourceCulture);
            }
        }
        
        public static string UsreouAllreadyRegisteredError {
            get {
                return ResourceManager.GetString("UsreouAllreadyRegisteredError", resourceCulture);
            }
        }
        
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        public static string ProcessingRequest {
            get {
                return ResourceManager.GetString("ProcessingRequest", resourceCulture);
            }
        }
        
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
    }
}
